steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-repo/bucket-backup:$SHORT_SHA
    - .

images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-repo/bucket-backup:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
